apiVersion: apps/v1
kind: Deployment
metadata:
  name: microgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microgateway

  template:
    metadata:
      labels:
        app: microgateway
    spec:
      containers:
        - name: microgateway
          image: sorinboia/arcadia-microgateway:v1
          imagePullPolicy: Always
          env:
            - name: ENV_CONTROLLER_API_URL
              value: https://$controller_ip:8443/1.4
            - name: ENV_CONTROLLER_API_KEY
              value: $controller_apikey
          ports:
            - containerPort: 80
            - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: microgateway
spec:
  selector:
    app: microgateway
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  externalTrafficPolicy: Local
  type: LoadBalancer