apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcadia-users-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcadia-login-sa
---
apiVersion: specs.smi-spec.io/v1alpha3
kind: HTTPRouteGroup
metadata:
  name: route-group
spec:
  matches:
    - name: destination-traffic
      methods:
        - GET

---
apiVersion: access.smi-spec.io/v1alpha2
kind: TrafficTarget
metadata:
  name: traffic-target
spec:
  destination:
    kind: ServiceAccount
    name: arcadia-users-sa
  rules:
    - kind: HTTPRouteGroup
      name: route-group
      matches:
        - destination-traffic
  sources:
    - kind: ServiceAccount
      name: arcadia-login-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-users
  template:
    metadata:
      labels:
        app: arcadia-users
    spec:
      serviceAccountName: arcadia-users-sa
      containers:
        - name: arcadia-users
          image: sorinboiaf5/arcadia-users:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-login
  template:
    metadata:
      labels:
        app: arcadia-login
    spec:
      serviceAccountName: arcadia-login-sa
      containers:
        - name: arcadia-login
          image: sorinboiaf5/arcadia-login:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80