apiVersion: v1
kind: Namespace
metadata:
  name: zipkin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim
          imagePullPolicy: Always
          ports:
            - containerPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
spec:
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: http
  selector:
    app: zipkin
